### ISSUE TITLE
cw_geodata.vector_label.polygon.geojson_to_px_gdf im_path

### ISSUE THREAD

**Issue by jshermeyer** [CosmiQ/cw-geodata#44]
cw_geodata.vector_label.polygon.geojson_to_px_gdf

im_path : str
        Path to a georeferenced image (ie a GeoTIFF) that geolocates to the
        same geography as the `geojson`(s). If a directory, the bounds of each
        GeoTIFF will be loaded in and all overlapping geometries will be
        transformed.

Based on my reading of this I assumed I could feed a directory containing multiple tif images, which fails.

**Comment by nrweir** [comment]
Thanks! Resolved with #45.
